services:
  validator:
    restart: on-failure
    image: registry.gitlab.com/shardeum/shardeum-server:1.0.0.0
    volumes:
      - data_vol:/app
    ports:
      - 9001:9001
    networks:
      default:
        aliases:
          - validator
      
  cli:
    restart: on-failure
    image: registry.gitlab.com/shardeum/validator-cli:0.0.0.1
    volumes:
      - data_vol:/app
    env_file: .env
    ports:
      - '10001:10001'
    networks:
      default:
        aliases:
          - cli
    depends_on:
      - validator

  gui:
    restart: on-failure
    image: registry.gitlab.com/shardeum/validator-gui:0.0.0.1
    volumes:
      - data_vol:/app
    env_file: .env
    ports:
      - '8080:8080'
    networks:
      default:
        aliases:
          - gui
    depends_on:
      - cli
      - validator

volumes:
  data_vol:
