version: '3.4'

services:
  shardeum-dashboard:
    container_name: shardeum-dashboard
    # network_mode: 'host'
    image: test-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
      # - './config.json:/usr/src/app/config.json:Z'
      # - './data/logs:/usr/src/app/logs:Z'
      # - './data/db:/usr/src/app/db:Z'
    # restart: 'always'
    env_file: .env
    ports:
      - '9003:9003'
      - '10003:10003'
      - '8888:8888'
      - '3001:3001'
